@ Generated by gcc 2.95.3 20010315 (release)(ColdFire patches - 20010318 from http://fiddes.net/coldfire/)(uClinux XIP and shared lib patches from http://www.snapgear.com/) for ARM/elf
	.file	"bubblesort.c"
.gcc2_compiled.:
.text
	.align	2
	.global	bubblesort
	.type	 bubblesort,function
bubblesort:
	@ args = 0, pretend = 0, frame = 20
	@ frame_needed = 1, current_function_anonymous_args = 0
	mov	ip, sp
	stmfd	sp!, {fp, ip, lr, pc}
	sub	fp, ip, #4
	sub	sp, sp, #20
	str	r0, [fp, #-16]
	str	r1, [fp, #-20]
	mov	r3, #0
	str	r3, [fp, #-24]
.L3:
	ldr	r3, [fp, #-24]
	ldr	r2, [fp, #-20]
	cmp	r3, r2
	blt	.L6
	b	.L4
.L6:
	mov	r0, r0	@ nop
	ldr	r3, [fp, #-24]
	str	r3, [fp, #-28]
.L7:
	ldr	r2, [fp, #-20]
	sub	r3, r2, #1
	ldr	r2, [fp, #-28]
	cmp	r2, r3
	blt	.L10
	b	.L5
.L10:
	ldr	r3, [fp, #-28]
	mov	r2, r3
	mov	r3, r2, asl #2
	ldr	r2, [fp, #-16]
	add	r3, r3, r2
	ldr	r1, [fp, #-28]
	mov	r2, #4
	mov	ip, r1, asl #2
	ldr	lr, [fp, #-16]
	add	r1, ip, lr
	add	r2, r1, r2
	ldr	r3, [r3, #0]
	ldr	r2, [r2, #0]
	cmp	r3, r2
	ble	.L9
	ldr	r3, [fp, #-28]
	mov	r2, r3
	mov	r3, r2, asl #2
	ldr	r2, [fp, #-16]
	add	r3, r3, r2
	ldr	r2, [r3, #0]
	str	r2, [fp, #-32]
	ldr	r3, [fp, #-28]
	mov	r2, r3
	mov	r3, r2, asl #2
	ldr	r2, [fp, #-16]
	add	r3, r3, r2
	ldr	r1, [fp, #-28]
	mov	r2, #4
	mov	ip, r1, asl #2
	ldr	lr, [fp, #-16]
	add	r1, ip, lr
	add	r2, r1, r2
	ldr	r1, [r2, #0]
	str	r1, [r3, #0]
	ldr	r2, [fp, #-28]
	mov	r3, #4
	mov	r1, r2, asl #2
	ldr	ip, [fp, #-16]
	add	r2, r1, ip
	add	r3, r2, r3
	ldr	r2, [fp, #-32]
	str	r2, [r3, #0]
.L11:
.L9:
	ldr	r3, [fp, #-28]
	add	r2, r3, #1
	str	r2, [fp, #-28]
	b	.L7
.L8:
.L5:
	ldr	r3, [fp, #-24]
	add	r2, r3, #1
	str	r2, [fp, #-24]
	b	.L3
.L4:
.L2:
	ldmea	fp, {fp, sp, pc}
.Lfe1:
	.size	 bubblesort,.Lfe1-bubblesort
