@ Generated by gcc 2.95.3 20010315 (release)(ColdFire patches - 20010318 from http://fiddes.net/coldfire/)(uClinux XIP and shared lib patches from http://www.snapgear.com/) for ARM/elf
	.file	"clear3.c"
.gcc2_compiled.:
.text
	.align	2
	.global	clear3
	.type	 clear3,function
clear3:
	@ args = 0, pretend = 0, frame = 16
	@ frame_needed = 1, current_function_anonymous_args = 0
	mov	ip, sp
	stmfd	sp!, {fp, ip, lr, pc}
	sub	fp, ip, #4
	sub	sp, sp, #16
	str	r0, [fp, #-16]
	str	r1, [fp, #-20]
	ldr	r3, [fp, #-20]
	mov	r2, r3
	mov	r3, r2, asl #2
	ldr	r2, [fp, #-16]
	add	r3, r2, r3
	str	r3, [fp, #-28]
	ldr	r3, [fp, #-16]
	str	r3, [fp, #-24]
.L3:
	ldr	r3, [fp, #-24]
	ldr	r2, [fp, #-28]
	cmp	r3, r2
	bcc	.L6
	b	.L4
.L6:
	ldr	r3, [fp, #-24]
	mov	r2, #0
	str	r2, [r3, #0]
.L5:
	ldr	r3, [fp, #-24]
	add	r2, r3, #4
	str	r2, [fp, #-24]
	b	.L3
.L4:
.L2:
	ldmea	fp, {fp, sp, pc}
.Lfe1:
	.size	 clear3,.Lfe1-clear3
