@ Generated by gcc 2.95.3 20010315 (release)(ColdFire patches - 20010318 from http://fiddes.net/coldfire/)(uClinux XIP and shared lib patches from http://www.snapgear.com/) for ARM/elf
	.file	"matrix.c"
.gcc2_compiled.:
.text
	.align	2
	.global	matrix
	.type	 matrix,function
matrix:
	@ args = 4, pretend = 0, frame = 32
	@ frame_needed = 1, current_function_anonymous_args = 0
	mov	ip, sp
	stmfd	sp!, {fp, ip, lr, pc}
	sub	fp, ip, #4
	sub	sp, sp, #32
	str	r0, [fp, #-16]
	str	r1, [fp, #-20]
	str	r2, [fp, #-24]
	str	r3, [fp, #-28]
	mov	r3, #0
	str	r3, [fp, #-32]
.L3:
	ldr	r3, [fp, #-32]
	ldr	r2, [fp, #-28]
	cmp	r3, r2
	blt	.L6
	b	.L4
.L6:
	mov	r3, #0
	str	r3, [fp, #-36]
.L7:
	ldr	r3, [fp, #-36]
	ldr	r2, [fp, #-28]
	cmp	r3, r2
	blt	.L10
	b	.L5
.L10:
	mov	r3, #0
	str	r3, [fp, #-44]
	mov	r3, #0
	str	r3, [fp, #-40]
.L11:
	ldr	r3, [fp, #-40]
	ldr	r2, [fp, #4]
	cmp	r3, r2
	blt	.L14
	b	.L12
.L14:
	ldr	r3, [fp, #-32]
	ldr	r2, [fp, #4]
	mul	r3, r2, r3
	ldr	r2, [fp, #-40]
	add	r3, r3, r2
	mov	r2, r3
	mov	r3, r2, asl #2
	ldr	r2, [fp, #-16]
	add	r3, r3, r2
	ldr	r2, [fp, #-40]
	ldr	r1, [fp, #-28]
	mul	r2, r1, r2
	ldr	r1, [fp, #-36]
	add	r2, r2, r1
	mov	r1, r2
	mov	r2, r1, asl #2
	ldr	r1, [fp, #-20]
	add	r2, r2, r1
	ldr	r3, [r3, #0]
	ldr	r2, [r2, #0]
	mul	r3, r2, r3
	ldr	r2, [fp, #-44]
	add	r3, r2, r3
	str	r3, [fp, #-44]
.L13:
	ldr	r3, [fp, #-40]
	add	r2, r3, #1
	str	r2, [fp, #-40]
	b	.L11
.L12:
	ldr	r3, [fp, #-32]
	ldr	r2, [fp, #-28]
	mul	r3, r2, r3
	ldr	r2, [fp, #-36]
	add	r3, r3, r2
	mov	r2, r3
	mov	r3, r2, asl #2
	ldr	r2, [fp, #-24]
	add	r3, r3, r2
	ldr	r2, [fp, #-44]
	str	r2, [r3, #0]
.L9:
	ldr	r3, [fp, #-36]
	add	r2, r3, #1
	str	r2, [fp, #-36]
	b	.L7
.L8:
.L5:
	ldr	r3, [fp, #-32]
	add	r2, r3, #1
	str	r2, [fp, #-32]
	b	.L3
.L4:
.L2:
	ldmea	fp, {fp, sp, pc}
.Lfe1:
	.size	 matrix,.Lfe1-matrix
