# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1458488046);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1474366810);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1474366689);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 34);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1475821714255");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1475825314255");
user_pref("browser.search.countryCode", "CN");
user_pref("browser.search.region", "CN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160209234718");
user_pref("browser.slowStartup.averageTime", 13651);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20160209234718");
user_pref("browser.startup.homepage_override.mstone", "44.0.2");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1458567829401");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1458481494850");
user_pref("datareporting.policy.firstRunTime", "1458481429400");
user_pref("datareporting.sessions.current.activeTicks", 0);
user_pref("datareporting.sessions.current.firstPaint", 19858);
user_pref("datareporting.sessions.current.main", 2429);
user_pref("datareporting.sessions.current.sessionRestored", 20022);
user_pref("datareporting.sessions.current.startTime", "1475821691649");
user_pref("datareporting.sessions.current.totalTime", 17);
user_pref("datareporting.sessions.currentIndex", 17);
user_pref("datareporting.sessions.previous.0", "{\"s\":1458481424516,\"a\":9,\"t\":75,\"c\":true,\"m\":825,\"fp\":10488,\"sr\":10071}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1458481986144,\"a\":1,\"t\":7,\"c\":true,\"m\":280,\"fp\":4975,\"sr\":4132}");
user_pref("datareporting.sessions.previous.10", "{\"s\":1458538882565,\"a\":3,\"t\":42,\"c\":true,\"m\":655,\"fp\":11061,\"sr\":11105}");
user_pref("datareporting.sessions.previous.11", "{\"s\":1458539365516,\"a\":6,\"t\":55,\"c\":true,\"m\":685,\"fp\":10019,\"sr\":10355}");
user_pref("datareporting.sessions.previous.12", "{\"s\":1458539640169,\"a\":1,\"t\":20,\"c\":true,\"m\":745,\"fp\":9561,\"sr\":9894}");
user_pref("datareporting.sessions.previous.13", "{\"s\":1458544012416,\"a\":7,\"t\":78,\"c\":true,\"m\":2272,\"fp\":35101,\"sr\":38765}");
user_pref("datareporting.sessions.previous.14", "{\"s\":1461747005844,\"a\":1,\"t\":10,\"c\":true,\"m\":785,\"fp\":7005,\"sr\":7112}");
user_pref("datareporting.sessions.previous.15", "{\"s\":1474366561663,\"a\":20,\"t\":257,\"c\":true,\"m\":1200,\"fp\":13485,\"sr\":13575}");
user_pref("datareporting.sessions.previous.16", "{\"s\":1475810059578,\"a\":3,\"t\":25,\"c\":true,\"m\":669,\"fp\":8646,\"sr\":9117}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1458482050696,\"a\":7,\"t\":36,\"c\":true,\"m\":303,\"fp\":4983,\"sr\":4635}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1458482389305,\"a\":2,\"t\":18,\"c\":true,\"m\":170,\"fp\":5693,\"sr\":5252}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1458485989420,\"a\":3,\"t\":30,\"c\":true,\"m\":1505,\"fp\":11652,\"sr\":11481}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1458487921658,\"a\":0,\"t\":240,\"c\":true,\"m\":927,\"fp\":10156,\"sr\":10786}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1458488167949,\"a\":1,\"t\":4,\"c\":true,\"m\":95,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.7", "{\"s\":1458537568948,\"a\":6,\"t\":61,\"c\":true,\"m\":736,\"fp\":7757,\"sr\":8054}");
user_pref("datareporting.sessions.previous.8", "{\"s\":1458537672151,\"a\":2,\"t\":13,\"c\":true,\"m\":81,\"fp\":3815,\"sr\":3610}");
user_pref("datareporting.sessions.previous.9", "{\"s\":1458537990924,\"a\":2,\"t\":13,\"c\":true,\"m\":91,\"fp\":3701,\"sr\":3948}");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.2,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:44.0.2");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "44.0.2");
user_pref("extensions.lastPlatformVersion", "44.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-global\":{\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"45.0\",\"st\":1457098132000},\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"45.0\",\"st\":1457098133000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"44.0.2\",\"st\":1455750937000,\"mt\":1455063905000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi\",\"e\":true,\"v\":\"3.2\",\"st\":1442597111000}}}");
user_pref("gecko.buildID", "20160209234718");
user_pref("gecko.mstone", "44.0.2");
user_pref("media.gmp-gmpopenh264.abi", "x86-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1458481498);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.buildID", "20160209234718");
user_pref("media.gmp-manager.lastCheck", 1474366640);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 51545);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateClearSavedPwdsOnExit", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1475821694);
user_pref("toolkit.telemetry.cachedClientID", "ea8c1a5c-f539-4e1c-ac23-26aa6c083902");
user_pref("toolkit.telemetry.previousBuildID", "20160209234718");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
